// Code generated by "stringer -type=ResultCode"; DO NOT EDIT.

package icinga

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-0]
	_ = x[WARNING-1]
	_ = x[CRITICAL-2]
	_ = x[UNKNOWN-3]
}

const _ResultCode_name = "OKWARNINGCRITICALUNKNOWN"

var _ResultCode_index = [...]uint8{0, 2, 9, 17, 24}

func (i ResultCode) String() string {
	if i < 0 || i >= ResultCode(len(_ResultCode_index)-1) {
		return "ResultCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResultCode_name[_ResultCode_index[i]:_ResultCode_index[i+1]]
}
